// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
//    repositories {
//        google()
//        mavenCentral()
//        maven { url "https://jitpack.io" } // 必须有
//    }
    dependencies {
        classpath libs.walle.plugin
    }
}


plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
//    alias(libs.plugins.kotlin.android) apply false
    id("com.google.devtools.ksp") version "2.2.10-2.0.2" apply false
}

apply from: "config.gradle"

//subprojects {
//    configurations.all {
//        resolutionStrategy.eachDependency { details ->
//            if (details.requested.group == 'org.jetbrains.kotlin') {
//                details.useVersion "2.0.21"
//            }
//        }
//    }
//}
allprojects {

    //此处为了解决mac M1芯片到问题 强制使用 sqlite版本
    configurations.all {
        resolutionStrategy {
            force 'org.xerial:sqlite-jdbc:3.34.0'
        }
    }
}