ext{
    android = [
            versionCode      : 21,
            versionName      : "2.0.1",
    ]
    dependencies = [

    ]




    appConfig = [

            "HOST"        :  "https://api.nunpingli.cn/",
            //TODO 隐私协议
            "privacyUrl": "http://api.nunpingli.cn/agreement/wlgxxj/privacy",
            "userUrl"   : "http://api.nunpingli.cn/agreement/wlgxxj/userr",
            "VERSIONNAME":android.versionName,

            //TODO 接口加密key

            "RELEASE_APPID": "0e0ea37c1b0bc622",
            "RELEASE_SSK"  : "9a85154af025395ec9e8f6bc7841efdb",


            //TODO 接口环境  日志log开关
            "logSwitch"    : true,

            //TODO 启动时间
            "IS_AGREEMENT":"2021-09-17 18:00:00",


            //TODO 友盟Id
            "umID":"6aacf3cb7431916083094c52",

            //TODO 第三方广告SDK ID
            "APPID"        : "5877580", //穿山甲Id


            "lx_tools_pt":"xiangji.aar"
    ]

}