ext{
    android = [
            versionCode      : 21,
            versionName      : "2.0.1",
    ]
    dependencies = [

    ]





    appConfig = [

            //TODO 隐私协议
            "privacyUrl": "https://api.zhangningjiang1.top/agreement/bbqfb/privacy",
            "userUrl"   : "https://api.zhangningjiang1.top/agreement/bbqfb/user",
            "VERSIONNAME":android.versionName,

            //TODO 接口环境  日志log开关
            "logSwitch"    : false,
            "APPID"    : "5865794",
            "umID"    : "6a9b88cb7431916083faab3f",

            "lx_tools_pt":"qingfangbao.aar"
    ]

}