ext{
    android = [
            versionCode      : 23,
            versionName      : "2.0.3",
    ]
    dependencies = [

    ]





    appConfig = [

            "HOST"        :  "https://api.zhangningjiang1.top/",
            //TODO 隐私协议
            "privacyUrl": "https://api.zhangningjiang1.top/agreement/dyfysq/privacy",
            "userUrl"   : "https://api.zhangningjiang1.top/agreement/dyfysq/user",
            "VERSIONNAME":android.versionName,

            //TODO 接口加密key

            "RELEASE_APPID": "7cc4b92143dca066",
            "RELEASE_SSK"  : "ab7190c549711c4efc36dac333fe867d",


            //TODO 接口环境  日志log开关
            "logSwitch"    : false,

            //TODO 启动时间
            "ad_LiveTime":"2026-08-25 18:00:00",


            //TODO 友盟Id
            "umID":"6a55f999cbfa69595177cb84",

            //TODO 第三方广告SDK ID
            "TOPON_APPID"  : "", //topOne Id
            "TOPON_APPKEY" : "", //topOne key
            "APPID"        : "5848932", //穿山甲Id
            "FISRT_SPLASH" : "",  //开屏
            "FIRST_REWORD" : "",//开屏激励视频
            "JL_APPID"     : "",//巨量appId


            "lx_tools_pt":"shell_duoyuyanfanyishengqi.aar"
    ]

}