pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        google()
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url "https://jitpack.io" }
        maven { url "https://artifact.bytedance.com/repository/pangle" }

        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }

        // 巨量广告转化 融合归因
        maven {
            url 'https://artifact.bytedance.com/repository/Volcengine/'
        }


    }

}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
//    id 'com.google.devtools.ksp' version '2.1.0-1.0.29' apply false
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url "https://jitpack.io" }
        maven { url "https://artifact.bytedance.com/repository/pangle" }

        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }

        // 巨量广告转化 融合归因
        maven {
            url 'https://artifact.bytedance.com/repository/Volcengine/'
        }
    }

}

rootProject.name = "LXToolsProject"
include ':app'
//include ':custom_honor_library'
include ':toolsbox'
include ':setting'
include ':hotSceniclib'
include ':sharedPreferences'
include ':scanlibrary'
include ':weather_lib'
include ':calculatorlibrary'
include ':h5_lib'

include ':tallynotes'
include ':pic_toolslibrary'
include ':pic_edit_library'
include ':smalltoolslibrary'
include ':toolslibrary'
include ':tools_extra_lib'
include ':color_picker_library'
//include ':c_interface_library'

 
//project(':custom_honor_library').projectDir =file('./modules/custom_honor_ad_library/custom_honor_library')
//project(':c_interface_library').projectDir =file('./modules/custom_honor_ad_library/c_interface_library')
project(':toolsbox').projectDir =file('./modulesUI/toolsbox_moduel/toolsbox')
project(':setting').projectDir =file('./modulesUI/third-module/setting')
project(':hotSceniclib').projectDir =file('./modulesUI/third-module/hotSceniclib')
project(':sharedPreferences').projectDir =file('./modulesUI/third-module/sharedPreferences')
project(':scanlibrary').projectDir =file('./modulesUI/third-module/scanlibrary')
project(':weather_lib').projectDir =file('./modulesUI/third-module/weather_lib')
project(':calculatorlibrary').projectDir =file('./modulesUI/third-module/calculatorlibrary')
project(':tallynotes').projectDir =file('./modulesUI/third-module/tallynotes')
project(':pic_toolslibrary').projectDir =file('./modulesUI/third-module/pic_toolslibrary')
project(':pic_edit_library').projectDir =file('./modulesUI/third-module/pic_edit_library')
project(':smalltoolslibrary').projectDir =file('./modulesUI/third-module/smalltoolslibrary')
project(':toolslibrary').projectDir =file('./modulesUI/third-module/toolslibrary')
project(':tools_extra_lib').projectDir =file('./modulesUI/third-module/tools_extra_lib')
project(':color_picker_library').projectDir =file('./modulesUI/third-module/color_picker_library')
project(':h5_lib').projectDir =file('./modulesUI/third-module/h5_lib')






include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:baidu_mobads_sdk_release'
include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:baidu_mobads_sdk_release_adapter'
include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:gdtsdk_unionnormal'
include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:gdtsdk_unionnormal_adapter'
include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:kssdk_ct_publishRelease'
include':modules:custom_honor_ad_library:custom_honor_library:aarlibrary:kssdk_ct_publishRelease_adapter'

