import com.github.megatronking.stringfog.plugin.StringFogMode
import com.stringf.gg.CustomKeyGenerator
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)

    id 'org.jetbrains.kotlin.android'
    id 'walle'
    id 'xml-class-guard'
    id 'android-junk-code'
    id 'stringfog'
    id 'top.niunaijun.blackobfuscator'

}
apply from: "${rootDir}/build_tools/jiagu/jiagu.gradle"


androidJunkCode {
    variantConfig {
        release {
            packageBase = "com.duqingshitianqi.sdfa.www"
            packageCount = 47
            activityCountPerPackage = 66
            excludeActivityJavaFile = false
            otherCountPerPackage = 84
            methodCountPerClass = 28
            resPrefix = "duqingshitianqi_"
            drawableCount = 198
            stringCount =  114
        }
    }
}



// 加入dex混淆配置
BlackObfuscator {
    // 是否启用
    enabled true
    // 混淆深度
    depth 2
    // 需要混淆的包或者类(匹配前面一段)
    obfClass = [
            "com.baidu.maps.utils",
            "com.lx.lxtoolsproject",
            "com.lx.lxtoolsproject.utils",
    ]
    // blackClass中的包或者类不会进行混淆(匹配前面一段)
    blackClass = ["top.niunaijun.black"]
}


stringfog {
    enable true
    debug false
    implementation 'com.stringf.gg.CustomStringFogImpl'
    // 4.0版本新增：使用自定义密钥生成器
    kg new CustomKeyGenerator()
    mode StringFogMode.base64
}


xmlClassGuard {
    mappingFile = file("xml-class-mapping.txt")
    //更改manifest文件的package属性，即包名
    packageChange = [
            "com.gzyf.jiandangshisaotong"  : "com.e.t",
    ]
    //移动目录
    moveDir = [
            "com.lx.lxtoolsproject"   : "com.ext.weather",
    ]
}


android {
    namespace 'com.lx.lxtoolsproject'
    compileSdk = 34
    	
    defaultConfig {
        applicationId "com.dgwcl.yunbihuisheng"
        minSdk 26
        targetSdk 33
        versionCode rootProject.ext.android["versionCode"]
        versionName rootProject.ext.android["versionName"]

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


        ndk { // 设置支持的 SO 库构架，注意这里要根据你的实际情况来设置
            abiFilters   "arm64-v8a"
        }



        buildConfigField "String","PRIVATE_URL",  "\"${rootProject.ext.appConfig["privacyUrl"]}\""
        buildConfigField "String","USER_URL",  "\"${rootProject.ext.appConfig["userUrl"]}\""
        buildConfigField "String","AD_LIVE_TIME",  "\"${rootProject.ext.appConfig["ad_LiveTime"]}\""
    }


    signingConfigs {
        release {
            keyAlias 'yunbihuisheng'
            keyPassword '123456'
            storeFile file('yunbihuisheng.jks')
            storePassword '123456'
        }
        debug {
            keyAlias 'yunbihuisheng'
            keyPassword '123456'
            storeFile file('yunbihuisheng.jks')
            storePassword '123456'
        }
    }




    buildTypes {

        release {
            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "LOG_DEBUG", "false"
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled false
            buildConfigField "boolean", "LOG_DEBUG", "false"
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        compose true
        buildConfig = true
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += [
                "-Xjvm-default=all",
        ]
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }


    dataBinding {
        enabled = true
    }

    viewBinding {
        enabled = true
    }

    buildFeatures {
        compose true
    }

    walle {
        // 指定渠道包的输出路径
        apkOutputFolder = new File("${project.buildDir}/outputs/channels");
        // 定制渠道包的APK的文件名称
        apkFileNameFormat = '云笔绘生-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}.apk';
        // 渠道配置文件
        channelFile = new File("${project.getProjectDir()}/channel/channel.txt")

    }


}

dependencies {
    implementation platform(libs.androidx.compose.bom)
//    implementation project(':custom_honor_library')
    implementation project(':c_interface_library')
    implementation project(':toolsbox')
//    implementation files('libs/'+rootProject.ext.appConfig["lx_tools_pt"])
//    implementation files('libs/'+rootProject.ext.appConfig["ad_aar"])
    implementation libs.androidx.activity.compose
    implementation libs.androidx.appcompat
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.ui
    implementation libs.com.blankj.utilcode
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.material
    implementation libs.io.coilkt
    testImplementation libs.junit
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    debugImplementation libs.androidx.compose.ui.test.manifest
    debugImplementation libs.androidx.compose.ui.tooling

    implementation ("androidx.appcompat:appcompat:1.6.1")
    implementation ("com.github.Petterpx.walle:library:1.0.4")
    implementation 'com.github.megatronking.stringfog:interface:5.0.0'
    implementation 'com.github.megatronking.stringfog:xor:5.0.0'
    implementation 'com.github.tiann:FreeReflection:3.1.0'
}

configurations.all {
    exclude group: 'com.intellij', module: 'annotations'
}