plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)

    id 'org.jetbrains.kotlin.android'
    id 'walle'


}
//apply plugin: 'walle'


android {
    namespace 'com.lx.lxtoolsproject'
    compileSdk = 34
    	
    defaultConfig {
        applicationId "com.szhc.zhiyusaomiaozhushou"
        minSdk 26
        targetSdk 33
        versionCode rootProject.ext.android["versionCode"]
        versionName rootProject.ext.android["versionName"]

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


        ndk { // 设置支持的 SO 库构架，注意这里要根据你的实际情况来设置
            abiFilters   "arm64-v8a"
        }



        buildConfigField "String","PRIVATE_URL",  "\"${rootProject.ext.appConfig["privacyUrl"]}\""
        buildConfigField "String","USER_URL",  "\"${rootProject.ext.appConfig["userUrl"]}\""
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs'] // 确保指向正确的目录
        }
    }


    signingConfigs {
        release {
            keyAlias 'zhiyusaomiaozhushou'
            keyPassword '123456'
            storeFile file('zhiyusaomiaozhushou.jks')
            storePassword '123456'
        }
        debug {
            keyAlias 'zhiyusaomiaozhushou'
            keyPassword '123456'
            storeFile file('zhiyusaomiaozhushou.jks')
            storePassword '123456'
        }
    }




    buildTypes {

        release {
            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "LOG_DEBUG", "false"
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled false
            buildConfigField "boolean", "LOG_DEBUG", "false"
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        compose true
        buildConfig = true
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += [
                "-Xjvm-default=all",
        ]
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }


    dataBinding {
        enabled = true
    }

    viewBinding {
        enabled = true
    }

    buildFeatures {
        compose true
    }
    	

    walle {
        // 指定渠道包的输出路径
        apkOutputFolder = new File("${project.buildDir}/outputs/channels");
        // 定制渠道包的APK的文件名称
        apkFileNameFormat = '智予扫描助手-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}.apk';
        // 渠道配置文件
        channelFile = new File("${project.getProjectDir()}/channel/channel.txt")

    }


}

dependencies {
    implementation platform(libs.androidx.compose.bom)
//    implementation project(':custom_honor_library')
    implementation project(':c_interface_library')
    implementation project(':toolsbox')
    implementation files('libs/'+rootProject.ext.appConfig["lx_tools_pt"])
//    implementation files('libs/'+rootProject.ext.appConfig["ad_aar"])
    implementation libs.androidx.activity.compose
    implementation libs.androidx.appcompat
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.ui
    implementation libs.com.blankj.utilcode
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.material
    implementation libs.io.coilkt
    testImplementation libs.junit
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    debugImplementation libs.androidx.compose.ui.test.manifest
    debugImplementation libs.androidx.compose.ui.tooling

    implementation ("androidx.appcompat:appcompat:1.6.1")
    implementation ("com.github.Petterpx.walle:library:1.0.4")


}

configurations.all {
    exclude group: 'com.intellij', module: 'annotations'
}