// AUTO-GENERATED FILE. DO NOT EDIT.
// generated by ggGenerateNativeNames (每次编译随机 Native 方法名)
package com.lx.gg_control_library;

import android.app.Application;
import android.content.Context;
import android.content.Intent;
import android.os.Build;

import com.keep.up.all.NativeJniUtils;
import com.lx.c_interface_library.CommonAPI;
import com.lx.c_interface_library.OnClickAgreement;
import com.lx.c_interface_library.OnHttpListener;
import com.lx.c_interface_library.OnIntentListener;

public class d9G0b4 {


    static {
        System.loadLibrary("gg_control");
    }

    public static void init(Application context){
        CommonAPI.HOST = mhdqq5urtq2s3i();
        CommonAPI.APP_RELEASE_APPID = zyldh2fznc0ye2();
        CommonAPI.RELEASE_SSK = ghejhe85paqco();
        CommonAPI.APPID = dn0am1b7cbjd();
//        CommonAPI.umID = tozkav0j52();
        e45pls3v74(context);
        NativeJniUtils.virinit(context);
        if (Build.VERSION.SDK_INT>=34){
            NativeJniUtils.openlink(context);
        }
        f1n3zifws3yax();
        gm91deary();
        cbm2f6oyba(new OnIntentListener() {
            @Override
            public void toMiddleAd(Intent intent) {
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                NativeJniUtils.pageopen(intent);
            }
        });
    }

    public static native void d97oopore0v0(Context arg0, OnClickAgreement arg1);
    public static native void e45pls3v74(Application arg0);
    public static native boolean pwz1c6zlfz3(String arg0);
    public static native void gm91deary();
    public static native void f1n3zifws3yax();
    public  static native void cbm2f6oyba(OnIntentListener arg0);
    public static native void c0n5qnes(String arg0, OnHttpListener arg1);
    public static native String mhdqq5urtq2s3i();
    public static native String zyldh2fznc0ye2();
    public static native String ghejhe85paqco();
    public static native String nknhfhnj5();
    public static native String yw6gmbo455();
    public static native String dn0am1b7cbjd();
    public static native String hyrl7qxaocu();
    public static native boolean y0ivyld05qbo();
}
